[package]
name = "time"
version = "0.3.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration"]
categories = ["date-and-time"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."
build = "build.rs"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["std"]
macros = ["time-macros"]
local-offset = ["std", "libc", "winapi", "stdweb", "cfg-if"]
std = ["standback/std"]
no-alloc = ["heapless"]

# Internal usage. This is used when building for docs.rs and time-rs.github.io.
# This feature should never be used by external users. It will likely be
# removed in the first release after the `doc_cfg` feature gets stabilized.
__doc = []

[dependencies]
cfg-if = { version = "0.1.10", optional = true }
rand = { version = "0.7", optional = true, default-features = false }
serde = { version = "1", optional = true, default-features = false, features = ["derive"] }
standback = { version = "0.2.5", default-features = false }
time-macros = { version = "0.2", path = "time-macros", optional = true }
heapless = { version = "0.5", optional = true }

[dev-dependencies]
time-macros = { version = "0.2", path = "time-macros" }

[build-dependencies]
version_check = "0.9"

[workspace]
members = ["time-macros", "time-macros-impl"]

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["minwinbase", "minwindef", "timezoneapi"], optional = true }

[target.'cfg(cargo_web)'.dependencies]
stdweb = { version = "0.4", default-features = false, optional = true }
